### ISSUE TITLE
🐛Inconsistent Behavior with Loot from Farms and Natural Mobs

### ISSUE THREAD

**Issue by cringoleg** [MarkusBordihn/BOs-Easy-Mob-Farm#45] opened 2023-10-22 18:49 UTC
#### **Overview**
Loot obtained from farms and naturally generated mobs are not treated as identical items, leading to discrepancies in stacking and crafting operations.

---

#### **Symptoms**
1. **Stacking Issue**: Drops from farms and loot from naturally spawned mobs are treated as distinct items, preventing them from stacking together.
2. **Crafting Issue**: When using farmed loot in a crafting recipe:
    - The game counts the loot towards the possible creation of the item.
    - However, the farmed loot isn't correctly placed in the crafting slots.

---

#### **Reproduction: Stacking Issue**

1. I placed an iron golem inside a creative farm:  
   ![Iron Golem](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/57872461/327229d3-1916-4094-bfb2-e7be094c97bf)
2. The loot from the farm resulted in:  
   ![Farmed Loot](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/57872461/95770329-2e91-4cac-b6b1-6836a42c30a3)
3. I then added 20 iron to my inventory using the `give` command.
4. I tried stacking the loot from the farm with the iron obtained through the `give` command but they didn't combine. This discrepancy becomes evident when using auto-sorting mods:  
   ![Stacking Issue](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/57872461/7672cc40-a995-4ba5-b17d-83f1ae75d8cc)

#### **Reproduction: Crafting Issue**

1. I collected 16 iron from the golem farm.
2. Added 64 sticks to my inventory.
3. When selecting the iron sword recipe (which the game considers doable with my inventory), only one stick is placed in the crafting table slots:  
   ![Crafting Issue](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/57872461/fd43550d-38ca-4b3c-af27-30b78f5800fd)
4. However, the game seems to recognize the total iron count. Pressing the recipe with `shift` places 8 sticks, corresponding to 8 potential iron swords (using the 16 iron):  
   ![Crafting Recognition](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/57872461/8ad18304-c5b4-4312-89d0-839ac764e69a)

---

#### **Expected Behavior**
Both loot from farms and natural spawns should be treated uniformly, allowing for seamless stacking and crafting operations.

---

#### **Environment**
Minecraft version: `1.19.4`
Mod Version: `6.8.0`

**Comment by MarkusBordihn** [comment] 2023-10-22 20:07
Could you please put both items in your hotbar and using the following command on each of the selected item:
`/data get entity @s SelectedItem`

This will show you the NBT data for each item like:
![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/bdfea06d-6942-4e7a-a217-1781289b2f6c)

If they are any difference in the name or other additional data, they will not stack.

**Comment by cringoleg** [comment] 2023-10-23 04:15
Here you go (16 is from farm, 1 is from creative inventory):
<img width="261" alt="image" src="https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/57872461/c75e8eec-e94d-44e8-9b2b-a5a9426aae7d">
Seems like the `tag:{}` kv breaks it.

**Comment by MarkusBordihn** [comment] 2023-10-23 11:48
Thanks for the additional details.

I run some tests and it seems that the issue is the quick move functionality.
So when you move the item manually with the mouse it's working as expected, but not if you using the quick move functionallity.

![image](https://github.com/MarkusBordihn/BOs-Easy-Mob-Farm/assets/12183293/b9848fb6-3678-4796-a73c-1f289930877f)

I will work on a fix.

**Comment by MarkusBordihn** [comment] 2023-10-23 21:07
This should be fixed with 6.9.0 which should be live in the next hours.

**Closed as completed by MarkusBordihn** 2023-10-23 21:07 UTC
Labels: bug
